/*
Script Category				: Implementation
Script Name    				: ki_hou_reference_codes_2.3.13.5.sql
Implementation Type(s)		: Housing Job Manager Integrated Solution
Description	   				: Reference Data
Run Context	   				: SQL*PLUS KIRONA schema
*/


SET TERMOUT ON
SET FEEDBACK ON

PROMPT Setting BIND Variables
VARIABLE ORG_ID NUMBER
BEGIN
:ORG_ID := &1;
END;
/

SET DEFINE OFF

BEGIN
application_utils.set_organisation(:ORG_ID);
application_utils.set_username('ki_hou_rc_23135.sql');
application_utils.set_version('2.3.13.5');
END;
/

REM **********************************************************************
REM            			REFERENCE CODES
REM **********************************************************************

REM **********************************************************************
REM            			REFERENCE DOMAIN PRETV_OF_NAME
REM **********************************************************************

PROMPT Reference Domain PRETV_OF_NAME low value: PRETV_TNT_GOING

UPDATE REF_CODES
SET  RV_MEANING='TENANT_MOVED_TO'
 WHERE RV_DOMAIN='PRETV_OF_NAME' AND RV_LOW_VALUE='PRETV_TNT_GOING';


PROMPT Reference Domain PRETV_OF_NAME low value: PRETV_VISIT_DATE

UPDATE REF_CODES
SET  RV_MEANING='PRETVVISITDATE'
 WHERE RV_DOMAIN='PRETV_OF_NAME' AND RV_LOW_VALUE='PRETV_VISIT_DATE';

REM **********************************************************************
REM            			REFERENCE DOMAIN PRETV_PROPELEMENT_CODE
REM **********************************************************************

PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: CP12DATE

UPDATE REF_CODES
SET  RV_MEANING='CP12DATE'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='CP12DATE';


PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: DOORENTRY

UPDATE REF_CODES
SET  RV_MEANING='DOOR'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='DOORENTRY';


PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: ENTRANCETYPE

UPDATE REF_CODES
SET  RV_MEANING='ENTR'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='ENTRANCETYPE';


PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: EXTERNALRAMP

UPDATE REF_CODES
SET  RV_MEANING='ARMP'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='EXTERNALRAMP';


PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: FLOORLEVEL

UPDATE REF_CODES
SET  RV_MEANING='FLOR'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='FLOORLEVEL';


PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: GARAGE

UPDATE REF_CODES
SET  RV_MEANING='GARG'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='GARAGE';


PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: GARDEN

UPDATE REF_CODES
SET  RV_MEANING='GAR'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='GARDEN';


PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: GREYWATER

UPDATE REF_CODES
SET  RV_MEANING='GREYWATER'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='GREYWATER';


PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: HEATINGTYPE

UPDATE REF_CODES
SET  RV_MEANING='HEAT'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='HEATINGTYPE';


PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: LIFT

UPDATE REF_CODES
SET  RV_MEANING='ALFT'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='LIFT';


PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: NOSTEPSACCESSFRONTDOOR

UPDATE REF_CODES
SET  RV_MEANING='STEP'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='NOSTEPSACCESSFRONTDOOR';


PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: NUMBEROFFLOORSINBLOCK

UPDATE REF_CODES
SET  RV_MEANING='FLOB'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='NUMBEROFFLOORSINBLOCK';


PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: NUMBEROFLIVINGROOMS

UPDATE REF_CODES
SET  RV_MEANING='ROOM'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='NUMBEROFLIVINGROOMS';


PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: NUMBEROFWCS

UPDATE REF_CODES
SET  RV_MEANING='NOWC'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='NUMBEROFWCS';


PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: NUM_BEDROOMS

UPDATE REF_CODES
SET  RV_MEANING='BEDS'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='NUM_BEDROOMS';


PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: SHOWER

UPDATE REF_CODES
SET  RV_MEANING='ASWR'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='SHOWER';


PROMPT Reference Domain PRETV_PROPELEMENT_CODE low value: SUBTYPE

UPDATE REF_CODES
SET  RV_MEANING='SUBT'
 WHERE RV_DOMAIN='PRETV_PROPELEMENT_CODE' AND RV_LOW_VALUE='SUBTYPE';

COMMIT;

PROMPT Checking and compiling invalid objects...

BEGIN
FOR i IN (SELECT 'ALTER '||DECODE(object_type,'PACKAGE BODY','PACKAGE', object_type ) ||' '||object_name||' compile ' || DECODE( object_type, 'PACKAGE BODY', 'BODY' ) sql_text
 FROM user_objects
 WHERE status = 'INVALID'
  AND object_type IN ('PACKAGE','VIEW','TRIGGER','PACKAGE BODY' )) LOOP
EXECUTE IMMEDIATE i.sql_text;
END LOOP;
END;
/

COL object_name FORMAT A30
SELECT object_name,object_type
FROM user_objects
WHERE status = 'INVALID'
/

exit 0;
